\LoadClass[11pt,a4paper,sans]{moderncv} % possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')


% moderncv themes
\moderncvstyle{banking}                            % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}                                % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}          
\RequirePackage{geometry} % changes margins across the page
 \geometry{
 left=15mm,
 right=15mm,
 top=15mm,
 bottom=5mm,
}
\RequirePackage{amssymb}
\RequirePackage{fontawesome5}
\RequirePackage{amsmath}


\newcommand{\college}{Universidad T\'ecnica Federico Santa Mar\'ia}	
\newcommand{\usm}{UTFSM}
\newcommand{\degree}{Ingeniero Civil Matem\'atico}
\newcommand{\valpoC} {Valpara\'iso, Chile}
\newcommand{\valpo} {Valpara\'iso}


% personal data
\name{Fabi\'an Castellano}{N\'u\~nez}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted

% \address{404 Rio Grande Street}{Austin, Texas, 78701}{USA}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
\phone[mobile]{+56~(9)~3229~7499}                   % optional, remove / comment the line if not wanted
\email{fabian.castellano@sansano.usm.cl}
\social[github][github.com/FabianCastellano]{fcastellano}
\homepage{fabiancastellano.github.io/about/}
\social[linkedin][www.linkedin.com/in/fabian-castellano/]{Fabian-Castellano}
